### ISSUE TITLE
C2 has to boot up after less than 24 hours

### ISSUE THREAD

**Issue by brittonx** [ShaneSmiskol/openpilot#169]
Stock Openpilot keeps the C2 powered for over 24 hours which has not caused any issues with the Prius 12V battery.  This fork more aggressively shuts down the C2 in far less than the 36-ish hours that stock OP does.  This makes running this fork a real hassle because I have to wait for the C2 to boot up.  Can we get an OP EDIT setting to go back to stock behavior for power management?

**Comment by ShaneSmiskol** [comment]
Since the time declarations are in the C++ file it's difficult to get opParams to read a param value, I've reverted the shutdown/charging time to stock, so it should stay on longer.

**Comment by brittonx** [comment]
Thank you!
