### ISSUE TITLE
Feature Request: Turn off screen when driving

### ISSUE THREAD

**Issue by suspi** [ShaneSmiskol/openpilot#295]
A feature that has me always running back to Dragonpilot is having the screen turn off after 30 seconds of inactivity (no user input or active alerts), even when driving. My EON has an annoying issue where it slowly drains the battery while engaged and the path indicator screen showing (about -1% every 5 minutes or so). It also quietly dodges the California device mounting requirement (dashboard, center console, or in the left lower corner of the front windshield).

**Comment by ShaneSmiskol** [comment]
If you have a commit showing how this is done while waking up for alerts, I'd merge it with a param possibly. Or you can open a pull request yourself to add this feature if you want!
