### ISSUE TITLE
Create new option for minimum speed for nudgeless lane change

### ISSUE THREAD

**Issue by hooser13** [ShaneSmiskol/openpilot#355]
Create an option for a minimum speed to conduct a nudgeless lane change.  For example, you can do nudgeless over 60 miles an hour and still require a nudge under 60 miles an hour.

**Comment by ShaneSmiskol** [comment]
Mind testing out the branch? @hooser13

**Comment by hooser13** [comment]
I really like the SA6.6.  I used to use DP and the steering wheel would oscillate constantly.  With SA, that's never a problem and steering wheel is stable.  I like your version of lane change because there isn't a delay before the lane change.  Much better.  The colors are nice with the lanes and turn radius.
